version: '3.1'

services:
    tekxit-dockerized:
        image: tekxit-dockerized
        build:
            context: ./src
            dockerfile: Dockerfile
        ports:
            - "${PORT:-25565}:25565"
        volumes:
            - "${SERVER_DIRECTORY:-./server}:/server"
